steps:
  # Step 1: Install Terraform into Cloud SDK image
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'Install Terraform'
    entrypoint: 'sh'
    args:
      - -c
      - |
        apt-get update && apt-get install -y unzip curl bash
        rm -rf terraform
        curl -fsSL https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip -o terraform.zip
        unzip -o terraform.zip
        chmod +x terraform
        mv terraform /usr/local/bin/
        terraform version

  # Step 2: Run Terraform Init & Apply in root directory
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'Terraform Init & Apply'
    entrypoint: 'sh'
    args:
      - -c
      - |
        apt-get update && apt-get install -y unzip curl bash
        rm -rf terraform
        curl -fsSL https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip -o terraform.zip
        unzip -o terraform.zip
        chmod +x terraform
        mv terraform /usr/local/bin/

        # Fetch secrets
        project_id=$(gcloud secrets versions access latest --secret=tf-project-id)
        project_number=$(gcloud secrets versions access latest --secret=tf-project-number)

        terraform init -input=false
        terraform plan -input=false -var="project_id=$project_id" -var="project_number=$project_number" -out=tfplan
        terraform apply -input=false -auto-approve tfplan

  # Step 3: Authenticate to GKE
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Authenticate to GKE'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials ecommerce-cluster \
          --region=us-central1 \
          --project=fine-proxy-464003-q4

  # Step 4: Deploy Orders Microservice
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'Deploy Orders Microservice'
    dir: helm/orders
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        helm upgrade --install orders . --namespace default --create-namespace

  # Step 5: Deploy Payments Microservice
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'Deploy Payments Microservice'
    dir: helm/payments
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        helm upgrade --install payments . --namespace default --create-namespace

  # Step 6: Deploy Users Microservice
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'Deploy Users Microservice'
    dir: helm/users
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        helm upgrade --install users . --namespace default --create-namespace

options:
  logging: CLOUD_LOGGING_ONLY

