steps:
  # Step 1: Install Terraform into Cloud SDK image
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'Install Terraform'
    entrypoint: 'sh'
    args:
      - -c
      - |
        apt-get update && apt-get install -y unzip curl bash
        rm -rf terraform
        curl -fsSL https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip -o terraform.zip
        unzip -o terraform.zip
        chmod +x terraform
        mv terraform /usr/local/bin/
        terraform version

  # Step 2: Run Terraform Init & Apply in root directory
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'Terraform Init & Apply'
    entrypoint: 'sh'
    args:
      - -c
      - |
        apt-get update && apt-get install -y unzip curl bash
        rm -rf terraform
        curl -fsSL https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip -o terraform.zip
        unzip -o terraform.zip
        chmod +x terraform
        mv terraform /usr/local/bin/

        # Fetch secrets
        project_id=$(gcloud secrets versions access latest --secret=tf-project-id)
        project_number=$(gcloud secrets versions access latest --secret=tf-project-number)

        terraform init -input=false
        terraform plan -input=false -var="project_id=$project_id" -var="project_number=$project_number" -out=tfplan
        terraform apply -input=false -auto-approve tfplan

options:
  logging: CLOUD_LOGGING_ONLY

